# Generated by Django 6.0.3 on 2026-03-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblarim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='blank.jpg', upload_to='books/'),
            preserve_default=False,
        ),
    ]
