# Generated by Django 6.0.3 on 2026-03-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblarim', '0003_order_alter_book_image_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilyapti'), ('shipped', 'Jo‘natildi'), ('delivered', 'Yetkazildi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitoblarim.order'),
        ),
    ]
